"""create users table

Revision ID: 071fbd0e2967
Revises: 
Create Date: 2026-01-26 01:43:45.502912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '071fbd0e2967'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=100), nullable=False),
    sa.Column('support', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('config_count', sa.Integer(), nullable=False),
    sa.Column('is_block', sa.Boolean(), nullable=False),
    sa.Column('step', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=True)
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reported_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reported_user'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_reported_user'), 'report', ['reported_user'], unique=False)
    op.create_index(op.f('ix_report_user_id'), 'report', ['user_id'], unique=False)
    op.create_index('ix_report_user_reported', 'report', ['user_id', 'reported_user'], unique=False)
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('providers', sa.String(length=100), nullable=False),
    sa.Column('type_product', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_vip', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_created_by_user_id'), 'service', ['created_by_user_id'], unique=False)
    op.create_table('details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(length=100), nullable=False),
    sa.Column('type_message', sa.String(length=50), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_details_service_id'), 'details', ['service_id'], unique=False)
    op.create_index(op.f('ix_details_user_id'), 'details', ['user_id'], unique=False)
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_dislike', sa.Boolean(), nullable=False),
    sa.Column('is_like', sa.Boolean(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_id', 'user_id', name='uq_likes_service_user')
    )
    op.create_index(op.f('ix_likes_service_id'), 'likes', ['service_id'], unique=False)
    op.create_index('ix_likes_service_user', 'likes', ['service_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_likes_user_id'), 'likes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_likes_user_id'), table_name='likes')
    op.drop_index('ix_likes_service_user', table_name='likes')
    op.drop_index(op.f('ix_likes_service_id'), table_name='likes')
    op.drop_table('likes')
    op.drop_index(op.f('ix_details_user_id'), table_name='details')
    op.drop_index(op.f('ix_details_service_id'), table_name='details')
    op.drop_table('details')
    op.drop_index(op.f('ix_service_created_by_user_id'), table_name='service')
    op.drop_table('service')
    op.drop_index('ix_report_user_reported', table_name='report')
    op.drop_index(op.f('ix_report_user_id'), table_name='report')
    op.drop_index(op.f('ix_report_reported_user'), table_name='report')
    op.drop_table('report')
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_table('setting')
    # ### end Alembic commands ###
